Ft-login
mwafrika/shift-plan-frontend pull request #5
Opened 2023-10-22 20:27 UTC by Irirwanirira

This PR Consist of: 

- [ ] structure login UI

2023-10-22 22:44 UTC, jefftrojan approved these changes

2023-10-25 07:20 UTC, alainburindi requested changes

2023-10-25 07:20 UTC, alainburindi commented on package.json
> +    "redux-thunk": "^2.4.2"
Redux is not used yet. Can we remove all these dependencies?

2023-10-25 08:50 UTC, ciraganenicole approved these changes

2023-11-16 05:12 UTC, closed without merging